// Generated by Wrangler on Wed Aug 14 2024 01:29:21 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
  ENV: string
  MICROCMS_SERVICE_DOMAIN: string
  MICROCMS_API_KEY: string
  GA_TRACKING_ID: string
  BUN_VERSION: string
}
